// home page screens
const String helloRahul = "Hello Rahul",
    r = "R",
    tradingOverview = "trading overview",
    five = "5",
    seventyEight = "78%",
    threeL = "+ ₹ 3L",
    unlockedCalls = "Unlocked Calls",
    successRate = "Success Rate",
    estimated = "Estimated P&L",
    ourRecommendations = "our recommendations",
    bajajFinance = "BAJAJ FINANCE",
    zero = "0",
tenMinuteAgo = "10 minute ago",
    threeHundredThirtyThree = "₹ 313",
    fourPointTwo = "4.2%",
    targetHits = "Target Hit",
    currentPrice = "Current Price",
    roi = "ROI",
    niftyMar = "NIFTY MAR 23",
    oneByFour = "1/4",
    threeHundredTwentyThree = "₹ 323",
    yourLiveCalls = "your live calls",
    eightPointTwo = "8.2%",
    topPerformingCall = "top performing calls",
    tataMotors = "TATA MOTORS",
    stocks = "STOCKS",
    options = "OPTIONS",
    three = "3",
    ourStrategyBuilders = "our strategy builders",
    forIntermediateInvestor = "For Intermediate Investors",
    forBeginnerInvestor = "For Beginner Investors",
    optionStrategyBuilders = "Options Strategy Builder",
    ourAI =
        "Our AI will curate a option strategy for you based on your market opinion.",
    yourStrategy =
        "Your strategies have been 30% accurate over the past 3 months",
    stocksEntry = "Stocks Entry Predictor",
    letUsKnow =
        "Let us know which stock you want to trade, and we'll give you the most competitive prices for its 'Entry' and 'Exit.'",
    yourStrategySeventy =
        "Your strategies have been 70% accurate over the past 3 months",
    yourStrategyEightySix =
        "Our strategies have been 86% accurate over the past 3 months",
    researchAndTools =
        "research and tools",
expertDesign = "Expert Designed Strategies",
theseAre = "These are Bot generated calls using expert strategies with the help of Artificial intelligence & Machine Learning",
    fill = "Fll / Dll \n",
    trin = "TRIN\nIndicator",
    sentiment = "Sentiment\nIndicator",
    pcrRadio = "PCR Ratio \n",
    maxPain = "Max Pain\nIndicator",
    technicalAnalysis = "Technical\nAnalysis",
    volumeAndDelivery = "Volume &\nDelivery Data",
    optionsOpenInterest = "Options\nOpen Interest",
    home = "Home",
    myTrades = "My Trades";